config/routes.rb
Rails.application.routes.draw do
  resources :feebacks
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations:'users/registrations'
  }
  post '/auth/login', to: 'authentication#login'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/feeback.rb
class Feeback < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable
  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::API
	before_action :configure_permitted_parameters, if: :devise_controller?
	
	protected
	
	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: %i[name avatar])
		devise_parameter_sanitizer.permit(:account_update, keys: %i[name avatar])
	end

	def not_found
    render json: { error: 'not_found' }
  end

  def authorize_request
    header = request.headers['Authorization']
    header = header.split(' ').last if header
    begin
      @decoded = JsonWebToken.decode(header)
      @current_user = User.find(@decoded[:user_id])
    rescue ActiveRecord::RecordNotFound => e
      render json: { errors: e.message }, status: :unauthorized
    rescue JWT::DecodeError => e
      render json: { errors: e.message }, status: :unauthorized
    end
  end
end

app/controllers/concerns/json_web_token.rb
require 'devise/jwt'

class JsonWebToken
	SECRET_KEY = Rails.application.secrets.secret_key_base. to_s

	def self.encode(payload, exp = 24.hours.from_now)
		payload[:exp] = exp.to_i
		JWT.encode(payload, SECRET_KEY)
	end

	def self.decode(token)
		decoded = JWT.decode(token, SECRET_KEY)[0]
		HashWithIndifferentAccess.new decoded
	end
end

app/controllers/feebacks_controller.rb
class FeebacksController < ApplicationController
  before_action :set_feeback, only: %i[ show edit update destroy ]
  before_action :authorize_request

  def index
    @feebacks = Feeback.all
  end

  def show
  end

  def new
    @feeback = Feeback.new
  end

  def edit
  end

  def create
    @feeback = Feeback.new(feeback_params)

      if @feeback.save
        render json: {message: 'feeback save'}
      else
        render json: {message: 'unauthorised'}
      end
  end

  private
    def set_feeback
      @feeback = Feeback.find(params[:id])
    end

    def feeback_params
      params.permit(:star_count)
    end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController

   def new
    @user = User.new
   end
  
   def create
    @user = User.new(user_registration_params)
    if @user.save
     render json: { message: 'Signed in successfully' }
    else
     render json: { message: 'User not created' }
    end
   end
  
   private
  
   def user_registration_params
    params.require(:user).permit(:email, :password)
   end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :authorize_request, except: :create

  def new
   @user = User.new
  end
  
  def create
     @user = User.find_by(email: user_params[:email])
    
     if @user && @user.valid_password?(user_params[:password])
      sign_in(@user)
      token = JsonWebToken.encode(user_id: @user.id)
			time = Time.now + 24.hours.to_i
			render json: { token: token, exp: time.strftime("%m-%d-%Y %H:%M"),
											email: @user.email }, status: :ok
     else
      render json: { message: 'Invalid email or password' }
     end
    end

  private
  
  def user_params
   params.require(:user).permit(:email,:password,:password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authentication_helper.rb
module AuthenticationHelper
end

app/helpers/feebacks_helper.rb
module FeebacksHelper
end

app/views/feebacks/_feeback.html.erb
<div id="<%= dom_id feeback %>">
</div>

app/views/feebacks/_form.html.erb
<%= form_with(model: feeback) do |form| %>
  <% if feeback.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(feeback.errors.count, "error") %> prohibited this feeback from being saved:</h2>

      <ul>
        <% feeback.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/feebacks/edit.html.erb
<h1>Editing feeback</h1>

<%= render "form", feeback: @feeback %>

<br>

<div>
  <%= link_to "Show this feeback", @feeback %> |
  <%= link_to "Back to feebacks", feebacks_path %>
</div>

app/views/feebacks/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Feebacks</h1>

<div id="feebacks">
  <% @feebacks.each do |feeback| %>
    <%= render feeback %>
    <p>
      <%= link_to "Show this feeback", feeback %>
    </p>
  <% end %>
</div>

<%= link_to "New feeback", new_feeback_path %>

app/views/feebacks/new.html.erb
<h1>New feeback</h1>

<%= render "form", feeback: @feeback %>

<br>

<div>
  <%= link_to "Back to feebacks", feebacks_path %>
</div>

app/views/feebacks/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @feeback %>

<div>
  <%= link_to "Edit this feeback", edit_feeback_path(@feeback) %> |
  <%= link_to "Back to feebacks", feebacks_path %>

  <%= button_to "Destroy this feeback", @feeback, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Railswithdeviseauthentication</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>